apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe7303-p-group-1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: SWE7303-P-GROUP-1-PROJECT
  template:
    metadata:
      labels:
        app: SWE7303-P-GROUP-1-PROJECT
    spec:
      containers:
        - name: SWE7303-P-GROUP-1-PROJECT
          image: devopsprojectg1/swe7303-p-group-1-project:1.0.0-21
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
