apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: swe7303pdevopsproject
  name: swe7303-p-group-1-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: SWE7303-P-GROUP-1-PROJECT
  template:
    metadata:
      labels:
        app: SWE7303-P-GROUP-1-PROJECT
    spec:
      containers:
        - image: devopsprojectg1/swe7303-p-group-1-project:1.0.0-21
          name: SWE7303-P-GROUP-1-PROJECT
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
